{% test cdc_source_staged(model) %}

{#-

This test determines whether the number of rows in the PSA table, and the Spectrum source table.
If the PSA table has no rows, and the test determines that the Spectrum source does have rows
that aren't staged, it will fail.

This tests for bugs inside cdc_psa_model, which if in-correct would trigger a failure here.
It can not catch infrastructure changes to the crawler, e.g. an incorrect location, DMS
task issue, or table rename.

-#}

{%- set source_relation = model -%}
{%- if execute -%}
    {#- This looks up the node name from the relation id, which should be valid if no alias is used. #}
    {%- set node = graph.nodes.get('model.' ~ project_name ~ '.' ~ model.identifier) -%}
    {#- The cdc_source_id is defined as a metadata field on the PSA tables. #}
    {%- set source_id = (node.config.get('meta') or {}).get('cdc_source_id') if node else none -%}

    {#- This checks to ensure that this test was applied to a valid model generated by cdc_psa_model #}
    {%- if not source_id -%}
        {{ exceptions.raise_compiler_error('failed to find cdc_source_id, unsupported test for' ~ model.identifier) }}
    {%- endif -%}

    {%- set source_relation = source(*source_id.split('.', 1)) -%}
{%- endif %}

select 1
where not exists (select 1 from {{ model }})
  and exists (select 1 from {{ source_relation }})

{% endtest %}
